// ============================================================
//  MICHWAR — Firebase Options
//  Generated by FlutterFire CLI. To regenerate:
//    1. Install CLI:  dart pub global activate flutterfire_cli
//    2. Run:          flutterfire configure
//  This will replace the placeholder values below with your
//  real Firebase project configuration.
// ============================================================
//
//  SETUP STEPS (one-time):
//  1. Go to https://console.firebase.google.com
//  2. Create a project named "michwar" (or any name)
//  3. Enable Authentication > Email/Password sign-in method
//  4. Enable Cloud Firestore (start in production mode)
//  5. Enable Storage
//  6. Add an Android app with package: com.example.michwar
//     (or whatever is in android/app/build.gradle applicationId)
//  7. Download google-services.json → place in android/app/
//  8. Run: flutterfire configure (auto-fills this file)
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Replace ALL placeholder values below with your real Firebase config ──

  // ── Web (admin PWA) — filled from Firebase Console ──────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO9HUpQvg1bA0qo8yPSj-N0uf8-SsYKsw',
    appId: '1:691204070078:web:c923eec5783c4045231cef',
    messagingSenderId: '691204070078',
    projectId: 'michwar-bfcca',
    authDomain: 'michwar-bfcca.firebaseapp.com',
    storageBucket: 'michwar-bfcca.firebasestorage.app',
    measurementId: 'G-PJ1QL3ZD50',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zi_tf6CcKkX8RCqnS4M7pKQ0h8RAPHE',
    appId: '1:691204070078:android:30680f114426555b231cef',
    messagingSenderId: '691204070078',
    projectId: 'michwar-bfcca',
    storageBucket: 'michwar-bfcca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '691204070078',
    projectId: 'michwar-bfcca',
    storageBucket: 'michwar-bfcca.firebasestorage.app',
    iosBundleId: 'com.example.michwar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '691204070078',
    projectId: 'michwar-bfcca',
    storageBucket: 'michwar-bfcca.firebasestorage.app',
    iosBundleId: 'com.example.michwar',
  );
}
